"""Made pct fields in picard VC nullable

Revision ID: b4aa6bb049b5
Revises: f67693ee953b
Create Date: 2025-11-07 13:02:40.347226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aa6bb049b5'
down_revision: Union[str, Sequence[str], None] = 'f67693ee953b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picard_variant_calling', schema=None) as batch_op:
        batch_op.alter_column('pct_gq0_variants',
                    existing_type=sa.FLOAT(),
                    nullable=True)
        batch_op.alter_column('pct_dbsnp',
                    existing_type=sa.FLOAT(),
                    nullable=True)
        batch_op.alter_column('pct_dbsnp_indels',
                    existing_type=sa.FLOAT(),
                    nullable=True)
        batch_op.alter_column('snp_reference_bias',
                    existing_type=sa.FLOAT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picard_variant_calling', schema=None) as batch_op:
        batch_op.alter_column('snp_reference_bias',
                existing_type=sa.FLOAT(),
                nullable=False)
        batch_op.alter_column('pct_dbsnp_indels',
                existing_type=sa.FLOAT(),
                nullable=False)
        batch_op.alter_column('pct_dbsnp',
                existing_type=sa.FLOAT(),
                nullable=False)
        batch_op.alter_column('pct_gq0_variants',
                existing_type=sa.FLOAT(),
                nullable=False)
    # ### end Alembic commands ###
